name: demoTest

on:
  pull_request:
    branches: 
      - main
      - feature

jobs:
  connect-remote:
    runs-on: ubuntu-latest

    services:
      mysql:

        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: Cloud_Projects
        
        ports:
          - 3306:3306
        

        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3


    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.18.0'
      
      - name: create and configure
        run: |
          touch .env
          echo DB_PORT=3306 >> .env
          echo DB_HOST=localhost >> .env
          echo DB_DIALECT=mysql >> .env
          echo DB_USER=root >> .env
          echo DB_PASSWORD=root >> .env
          echo DB_DATABASE=Cloud_Projects >> .env
          cat .env
      
      - name: Install dependencies
        run: npm install
      
      - name: Run tests
        run: npm test