name: demoTest

on:
  pull_request:
    branches: 
      - main
      - feature

jobs:
  connect-remote:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: "KJSCE2018grad##"
          MYSQL_DATABASE: "Cloud_Projects"
          MYSQL_ROOT_HOST: "%"
          # MYSQL_ALLOW_EMPTY_PASSWORD : "yes"
          # MYSQL_DATABASE: "Cloud_Projects"
          # MYSQL_ROOT_HOST: "%"

          # DB_HOST: 127.0.0.1
          # # DB_CONNECTION: mysql
          # DB_DATABASE: "Cloud_Projects"
          # DB_PORT: 3306
          # DB_USER: root
          # DB_PASSWORD: "KJSCE2018grad##"
          # MYSQL_ROOT_PASSWORD: "KJSCE2018grad##"
          # MYSQL_ROOT_PASSWORD: root
          # MYSQL_DATABASE: "Cloud_Projects"
          # MYSQL_ROOT_HOST: 127.0.0.1
          # MYSQL_USER: root
          # MYSQL_PASSWORD: "KJSCE2018grad##"
        
        # run: |
        #   sudo /etc/init.d/mysql start
        ports:
          - 3306:3306
        
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=10s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.18.0'
      
      - name: create and configure
        run: |
          touch .env
          echo port= 3306 >> .env
          echo host= localhost >> .env
          echo dialect= mysql >> .env
          echo user= root >> .env
          echo password= KJSCE2018grad## >> .env
          echo database= Cloud_Projects >> .env
      
      - name: Install dependencies
        run: npm install
      
      - name: Run tests
        run: npm test