name: Build custom AMI
on:
  push:
    branches: [ "main" ]

jobs:
  integrationTest:
    runs-on: ubuntu-latest

    services:
      mysql:

        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: Cloud_Projects
        
        ports:
          - 3306:3306
        

        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.18.0'
      
      - name: create and configure
        run: |
          touch .env
          echo DB_PORT=3306 >> .env
          echo DB_HOST=localhost >> .env
          echo DB_DIALECT=mysql >> .env
          echo DB_USER=root >> .env
          echo DB_PASSWORD=root >> .env
          echo DB_DATABASE=Cloud_Projects >> .env
          echo USERS_CSV_PATH=./data/users.csv >> .env
          echo STATSD_HOST=localhost >> .env
          echo STATSD_PORT=8125 >> .env
          echo LOGS_FILE_PATH=./logs/webapp.log >> .env
          echo SNS_TOPIC_ARN=${{ secrets.AWS_DEV_SNS_ARN }} >> .env
          echo AWS_REGION="us-east-1" >> .env
          echo AWS_PROFILE=dev >> .env
          cat .env
      
      - name: Install dependencies
        run: npm install
      
      - name: Run tests
        run: npm test
  
  packerValidate:
    name: Validate packer AMI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Compress codebase
      #   run:  zip -r webapp.zip .  --exclude='.git' --exclude='.github' --exclude='.vscode' --exclude='node_modules' --exclude='logs' --exclude="package-lock.json" --exclude=".env" .
        
      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_GIT_DEV_ACCESS_KEY }}
      #     aws-secret-access-key: ${{ secrets.AWS_GIT_DEV_SECURITY_KEY }}
      #     aws-region: 'us-east-1'

      - name: Setup packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest"

      - name: Run `packer init`
        id: init
        run: "packer init ./packer/debian-ami-aws.pkr.hcl"  

      - name: Run 'packer format'
        id: packer-format
        run: "packer fmt -check=true -write=false -diff=true ./packer/debian-ami-aws.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        run: "packer validate ./packer/debian-ami-aws.pkr.hcl"

  build:
    name: Build packer AMI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compress codebase
        run:  zip -r webapp.zip .  --exclude='.git' --exclude='.github' --exclude='.vscode' --exclude='node_modules' --exclude='logs' --exclude="package-lock.json" --exclude=".env" .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_GIT_DEV_ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.AWS_GIT_DEV_SECURITY_KEY }}
            aws-region: 'us-east-1'

      - name: Setup packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest"

      - name: Run `packer init`
        id: init
        run: "packer init ./packer/debian-ami-aws.pkr.hcl"  
  
      - name: Run 'packer format'
        id: packer-format
        run: "packer fmt -check=true -write=false -diff=true ./packer/debian-ami-aws.pkr.hcl"
  
      - name: Run `packer validate`
        id: validate
        run: "packer validate ./packer/debian-ami-aws.pkr.hcl"

      - name: Build `packer build`
        id: build
        run: "packer build ./packer/debian-ami-aws.pkr.hcl"
  
      - name: Reconfigure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_GIT_DEMO_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_GIT_DEMO_SECURITY_KEY }}
          aws-region: ${{vars.AWS_REGION}}
      
      - name: Create new launch template version and refresh
        id: deploy
        run: |
          image_id=$(aws ec2 describe-images --filters 'Name=name,Values=packer-debian-12-ami*' --query 'sort_by(Images, &CreationDate)[-1].[ImageId]' --output 'text')
          echo '"'$image_id'"'
          aws ec2 create-launch-template-version --launch-template-name '${{vars.LAUNCH_TEMPLATE_NAME}}' --source-version '$Latest' --launch-template-data "{\"ImageId\":\"$image_id\"}"
          aws autoscaling start-instance-refresh --auto-scaling-group-name '${{vars.AUTOSCALING_GROUP_NAME}}' --desired-configuration '{"LaunchTemplate": {"LaunchTemplateName": "${{vars.LAUNCH_TEMPLATE_NAME}}", "Version": "$Latest"}}'
      
      
      