name: Validate packer AMI
on:
  pull_request:
    branches:  
    - main
    - feature 

jobs:
  build:
    name: Validate packer AMI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compress codebase
        run:  zip -r webapp.zip .  --exclude='.git' --exclude='.github' --exclude='.vscode' --exclude='node_modules' --exclude='logs' --exclude="package-lock.json" --exclude=".env" .
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_GIT_DEV_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_GIT_DEV_SECURITY_KEY }}
          aws-region: 'us-east-1'

      - name: Setup packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest"

      - name: Run `packer init`
        id: init
        run: "packer init ./packer/debian-ami-aws.pkr.hcl"  

      - name: Run 'packer format'
        id: packer-format
        run: "packer fmt -check=true -write=false -diff=true ./packer/debian-ami-aws.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        run: "packer validate ./packer/debian-ami-aws.pkr.hcl"